---
################################################################################
# tap repositories                                                             #
################################################################################

- name: Tap homebrew repositories
  homebrew_tap: tap={{ item }}
  with_items: "{{ dev.homebrew_taps }}"

################################################################################
# Apache install                                                               #
################################################################################

- name: Stop system Apache
  become: yes
  command: apachectl stop

- name: Unload system Apache Deamon
  become: yes
  shell: "launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist 2>/dev/null"

- name: Install Apache 2.4 from brew
  homebrew:
    name: httpd24
    state: latest
    install_options: with-privileged-ports, with-http2

################################################################################
# PHP install                                                                  #
################################################################################

- name: Install PHP
  homebrew:
    name: php56
    state: latest
    install_options: with-httpd24

################################################################################
# software install                                                             #
################################################################################

- name: Install apps via `brew cask`
  homebrew_cask: name="{{ item }}" # install_options="appdir={{ homebrew_cask_appdir }}"
  with_items: "{{ dev.homebrew_cask_apps }}"

- name: Install configured homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: "{{ dev.homebrew_packages }}"

- name: Install npm packages
  npm: name={{ item }} global=yes state=present
  with_items: "{{ dev.npm_packages }}"

- name: Install gem packages
  gem: name={{ item }} state=present user_install=no
  with_items: "{{ dev.gem_packages }}"
