---
homebrew_cask_appdir: /Applications
dev:
  homebrew_taps:
    - caskroom/cask
    - homebrew/php
    - homebrew/versions
    - homebrew/services

  homebrew_packages:
    - tree
    - wget
    - fish
    - bash
    - pv
    - ssh-copy-id
    - redis
    - mysql56
    - php56-xdebug
    - php56-intl
    - php56-redis
    - php56-imagick
    - php56-mcrypt
    - php56-opcache
    - php56-apcu
    - php56-yaml
    - composer
    - imagemagick
    - elasticsearch
    - heroku-toolbelt
    - node
    - nvm
    - dnsmasq
    - homebrew/dupes/rsync
    - coreutils
    - symfony-installer
    - yarn

  homebrew_cask_apps:
    - atom
    - cocoarestclient
    - docker
    - firefox
    - google-chrome
    - phpstorm
    - iterm2
    - java
    - skype
    - slack
    - vagrant
    - virtualbox
    - wkhtmltopdf
    - sequel-pro
    - robomongo

  npm_packages:
    - gulp

  gem_packages:
    - hologram

  services:
    - name: dnsmasq
      root: true
    - name: httpd
      root: true
    - name: mysql56
      root: false
    - name: elasticsearch
      root: false
    - name: redis
      root: false
