# TODO: adjust to this mac-setup
---
- hosts: local
  connection: local

  vars_files:
    - vars/dev.yml

  tasks:
    - name: Reinstall php versions
      shell: "brew reinstall {{ item }} --with-httpd24 --build-from-source; brew unlink {{ item }};"
      with_items: "{{ dev.php_versions }}"

    - name: Reinstall php extensions
      shell: "brew link {{ item[0] }}; brew reinstall {{ item[0] ~ '-' ~ item[1] }} --build-from-source; brew unlink {{ item[0] }};"
      with_nested:
        - "{{ dev.php_versions }}"
        - "{{ dev.php_extensions }}"

    - name: Remove PHP modules
      lineinfile:
        dest: /usr/local/etc/httpd/httpd.conf
        regexp: "^#?LoadModule php[5|7]_module*"
        state: absent

    - name: Add PHP 5 module
      lineinfile:
        dest: /usr/local/etc/httpd/httpd.conf
        regexp: "^LoadModule php5_module /usr/local/lib/libphp5.so"
        insertafter: "^LoadModule rewrite_module libexec/mod_rewrite.so"
        line: "LoadModule php5_module /usr/local/lib/libphp5.so"
        state: present

    - name: Add PHP 7 module
      lineinfile:
        dest: /usr/local/etc/httpd/httpd.conf
        regexp: "^#LoadModule php7_module /usr/local/lib/libphp7.so"
        insertafter: "^LoadModule php5_module /usr/local/lib/libphp5.so"
        line: "#LoadModule php7_module /usr/local/lib/libphp7.so"
        state: present
